spring:
  application:
    name: code-challenge

  cloud:
    config:
      import-check:
        enabled: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-main.yaml


# Logging
logging:
  file:
    name: logs/app.log   # Logback will use this via ${LOG_FILE}

  level:
    root: INFO
    org.springdoc: INFO
    org.hibernate.SQL: INFO

# Actuator & Metrics
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      percentiles-histogram:
        http.server.requests: true
        notification.processing: true

# Server
server:
  port: 8080
  shutdown: graceful